"""Splits the official Eldapoint Group logo (the live header SVG) into the parts the preloader animates.

Source: https://www.eldapoint-group.co.uk/wp-content/uploads/2023/12/eldapoint-group-logo-web-header-300px.svg
(saved in _scrape/live/images). It is already drawn shape by shape:
  - one red path: the chevron band (a road running right, then rising)
  - one red path: the dot of the i
  - white letterforms for "Eldapoint" (the l is a polygon and the i stem a rect; both are turned into paths)
  - "GROUP" as five letters (the file carries them twice, stacked; one copy is kept)
Writes lib/logo.ts. Run with `npm run logo`.
"""
import json, re, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
svg = (root / "_scrape/live/images/eldapoint-group-logo-web-header-300px.svg").read_text()

shapes = []
for m in re.finditer(r'<(path|polygon|rect)([^>]*)/?>', svg):
    tag, attrs = m.group(1), m.group(2)
    cls = re.search(r'class="([^"]+)"', attrs).group(1)
    if tag == "path":
        d = re.search(r' d="([^"]+)"', attrs).group(1)
    elif tag == "polygon":
        pts = re.search(r'points="([^"]+)"', attrs).group(1).split()
        xy = [pts[i:i + 2] for i in range(0, len(pts), 2)]
        d = "M" + " L".join(f"{x} {y}" for x, y in xy) + "Z"
    else:
        g = {k: float(re.search(rf'{k}="([^"]+)"', attrs).group(1)) for k in ("x", "y", "width", "height")}
        d = f"M{g['x']} {g['y']}h{g['width']}v{g['height']}h-{g['width']}Z"
    first = re.match(r'[mM]\s*([-\d.]+)[ ,]*([-\d.]+)', d)
    shapes.append({"cls": cls, "d": d, "x": float(first.group(1)), "y": float(first.group(2))})

band = shapes[0]["d"]
dot = next(s for s in shapes if s["cls"] == "cls-1" and s is not shapes[0])
white = [s for s in shapes if s["cls"] == "cls-2"]
group, seen = [], set()
for s in white:
    if s["y"] > 70 and s["d"] not in seen:          # GROUP sits on the band, below y 70; drop the duplicate copy
        seen.add(s["d"]); group.append(s)
letters = [s for s in white if s["y"] <= 70]

# Order letters by the point each path starts at; for this file that is left to right (the E starts at its
# top-right corner, 18.13, which is still left of the l at 26.52).
letters.sort(key=lambda s: s["x"])
group.sort(key=lambda s: s["x"])

out = f"""// Generated by scripts/logo.py from the official header SVG. Do not edit by hand.
export const VIEWBOX = "0 0 300 87.65";
export const LOGO_W = 300;
export const LOGO_H = 87.65;
/** The red chevron band: a road running right under the name, then rising (#DF362C in the source file). */
export const BAND = {json.dumps(band)};
/** "Eldapoint", one path per letterform, left to right (E, l, d, a, p, o, i, n, t). */
export const LETTERS = {json.dumps([s["d"] for s in letters])};
/** The red dot of the i. */
export const DOT = {json.dumps(dot["d"])};
/** "GROUP", one path per letter, left to right; white on the band. */
export const GROUP = {json.dumps([s["d"] for s in group])};
"""
(root / "lib/logo.ts").write_text(out)
print(f"band 1, letters {len(letters)}, dot 1, group {len(group)}")
